# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='memberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=100, verbose_name='Full Name')),
                ('memberGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('memberLocation', models.CharField(max_length=100, verbose_name='Location')),
                ('memberContactNumber', models.IntegerField(max_length=14, verbose_name='Contact Number')),
                ('memberEmail', models.EmailField(max_length=100, verbose_name='Email ID')),
                ('memberRegistrationDate', models.DateTimeField(verbose_name='Registration Date')),
                ('memberStatus', models.BooleanField(default=True, verbose_name='Status')),
                ('memberUserNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
