# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberSocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('linkedin', models.CharField(max_length=100, verbose_name='LinkedIn')),
                ('github', models.CharField(max_length=100, verbose_name='Github')),
                ('googleplus', models.CharField(max_length=100, verbose_name='GooglePlus')),
                ('stackoverflow', models.CharField(max_length=100, verbose_name='Stackoverflow')),
                ('memberUserNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
