# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetails', '0002_membersocialnetworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='memberStatus',
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberAge',
            field=models.IntegerField(default=20, max_length=3, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberOccupation',
            field=models.CharField(default=123, max_length=100, verbose_name='Occupation'),
            preserve_default=False,
        ),
    ]
