# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetails', '0004_auto_20171114_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='memberdesc1',
            field=models.CharField(default=1, max_length=500, verbose_name='Description1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberdesc2',
            field=models.CharField(default=2, max_length=500, verbose_name='Description2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberdesc3',
            field=models.CharField(default=3, max_length=500, verbose_name='Description3'),
            preserve_default=False,
        ),
    ]
