# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetails', '0005_auto_20171116_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='memberURLUserName',
            field=models.CharField(default=33, max_length=15, unique=True, verbose_name='User Name'),
            preserve_default=False,
        ),
    ]
